// Generated by scripts/generate-build-info.mjs. Do not edit manually.
export const BUILD_INFO = Object.freeze({
  buildRevision: "b652c648889993be31656c429b5dc3b86782e7d2b84a4450fcb994c565c606c9",
  toolSchemaRevision: "abeddf4a9b8849022838c396d6e7de7d628350807129d30a2c8647c58d7a40c9",
});
