// Generated by scripts/generate-build-info.mjs. Do not edit manually.
export const BUILD_INFO = Object.freeze({
  buildRevision: "12b0d3f7c8de1f74287598c9234f7b417704a495daa528b5be5a2466e5cf10ef",
  toolSchemaRevision: "3df6202aabbde27e6843de2d1705651c9ec8f866d46ce5cbf73541ccf2bd1c2d",
});
