// Generated by scripts/generate-build-info.mjs. Do not edit manually.
export const BUILD_INFO = Object.freeze({
  buildRevision: "3ef707f5f8d521edb384554abe3eeaa57e33e3066539ab99ccd444a6922cc096",
  toolSchemaRevision: "09e49b5f4029fe85689dbd2335949b659029cbd261d04ba4fe4f483eb0779c9d",
});
